apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: kube-vm
data:
  alertmanager.yml: |
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'web.hook'
    receivers:
      - name: 'web.hook'
        webhook_configs:
         #- url: 'http://172.16.59.106:41679/alarm/alertmanager'
          - url: 'http://172.21.53.240:41679/alarm/alertmanager'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
