apiVersion: v1
kind: ConfigMap
metadata:
  name: dsp-vmagent-config
  namespace: kube-victoriametrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
    scrape_configs:
    - job_name: "sh-dsp-engine"
      metrics_path: /actuator/prometheus
      # params:
      #   portlist: [ ":80", "127.0.0.1:9100" ]
      #   httplist: [ "https://www.baidu.com", "https://www.hao123.com" ]
      # 抓取node_exporter
      #tls_config:
      #  insecure_skip_verify: true
      #bearer_token_file: secret/sh-dsp-node-token
      kubernetes_sd_configs:
      - role: pod
        api_server: https://172.21.51.242
        authorization:
          credentials: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJzZW5odWEtcHJvbWV0aGV1cy10b2tlbi1ycHAyaiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJzZW5odWEtcHJvbWV0aGV1cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjdhY2I1OGQ1LTEzNzgtMTFlYi1iZWRjLTZjOTJiZjk2YjczOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpzZW5odWEtcHJvbWV0aGV1cyJ9.zPX676Fiz81kqlElL9LBCh1geO13OIqnHVP5-5xNjNjyRaXjjLCuZaV-2BEAzgw951V4zsllNIqsl-z9sJKroJd9806wCFjJq6wX1rRooqosVtFNivj3_KqFbM1guW6MKnZeiyp4as4_vXIpr2Ub0uz-Q6UtnQKL7Wmqi3osDfBqo95c7CcTyJ3Fl3l09HRRxZS-vCCE2UGjqy8vPuzm_3-MudoJe-GMGWP6QL9h8HzXgo-wBvD6XuQqCwAVECd39JeM1z89dsJp36Oosz7tmNkhNMiqNVzH6-Yt16S-OAJsSLQNX6bBJyEpcylw3UfOUQYaRshJxGB-DI0NYj2y4Q"
          #credentials_file: secret/sh-dsp-token
        tls_config:
          # ca_file: secret/sh-dsp-ca.crt
          insecure_skip_verify: true
        #bearer_token_file: secret/sh-dsp-token
        namespaces:
          names:
            [ "dsp" ]
        selectors:
        - role: "pod"
          label: "app in (jsearchserver-v2, jsearchserver-v3)"
      relabel_configs:
      - source_labels: ["__meta_kubernetes_pod_host_ip", "__meta_kubernetes_pod_container_port_number"]
        regex: '(.*);(8080|8081)'
        replacement: '${1}:${2}'
        target_label: address
        action: keep
      - source_labels: ["__meta_kubernetes_pod_host_ip", "__meta_kubernetes_pod_container_port_number"]
        regex: '(.*);(8080|8081)'
        replacement: '${1}:${2}'
        target_label: __address__