apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: senhua-vm
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: senhua-vm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: senhua-vm
subjects:
- kind: ServiceAccount
  name: senhua-vm
  namespace: kube-system
