apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vmagent
  namespace: kube-vm
  labels:
    app: vmagent
spec:
  serviceName: vmagent
  replicas: 3
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      hostAliases:
      - ip: "172.21.52.240"
        hostnames:
        - "k8s-api.virtual.local"
      containers:
        - name: vmagent
          image: victoriametrics/vmagent:latest
          imagePullPolicy: IfNotPresent
          args:
            - -promscrape.cluster.membersCount=2
            - -promscrape.cluster.memberNum=$(MY_POD_NAME)
            - -promscrape.cluster.replicationFactor=2
            - -promscrape.suppressScrapeErrors
            # 每隔30s检测配置文件是否更新
            - -promscrape.configCheckInterval=30s
            # -remoteWrite.tmpDataPath=/victoriametrics-data/vmagent
            # -remoteWrite.maxDiskUsagePerURL=1GB
            # default :8429
            # -httpListenAddr=":${VMAGENT_PORT}"
            - -promscrape.config=/data/vmagent/config/prometheus.yml
            # 这里ACCOUNT_ID是1  1是sre的所有指标存放账户
            - -remoteWrite.url=http://vminsert:8480/insert/1/prometheus/api/v1/write
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          volumeMounts:
          - name: config
            mountPath: /data/vmagent/config
            # 使用 ConfigMap 作为 subPath 卷挂载的容器将不会收到 ConfigMap 的更新。
            # mountPath: /victoriametrics-data/vmagent/config/prometheus.yml
            # subPath: prometheus.yml
            readOnly: true
          readinessProbe:
            tcpSocket:
              port: 8429
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8429
            initialDelaySeconds: 60
            periodSeconds: 3
          ports:
          - name: vmagent-http
            containerPort: 8429
            protocol: TCP
      nodeSelector:
        # kubernetes.io/role=ops-node
        service: vm
      volumes:
      - name: config
        configMap:
          name: vmagent-config
          # 来自 ConfigMap 的一组键，将被创建为文件
          items:
          - key: "prometheus.yml"
            path: "prometheus.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: vmagent
  namespace: kube-vm
  labels:
    app: vmagent
spec:
  type: NodePort
  ports:
  - port: 8429
    targetPort: vmagent-http
    protocol: TCP
  selector:
    app: vmagent
