apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmselect
  namespace: kube-vm
  labels:
    app: vmselect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vmselect
  template:
    metadata:
      labels:
        app: vmselect
    spec:
      containers:
        - name: vmselect
          image: victoriametrics/vmselect:latest
          imagePullPolicy: IfNotPresent
          args:
            - -dedup.minScrapeInterval=30s
            # 数据存储的副本数
            - -replicationFactor=2
            - -storageNode=172.30.33.205,172.30.8.171
            # default :8481
            # - -httpListenAddr=":8481"
          ports:
          - name: vmselect-tcp
            containerPort: 8481
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8481
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8481
            initialDelaySeconds: 30
            periodSeconds: 3
      nodeSelector:
        # kubernetes.io/role=ops-node
        service: vm
---
apiVersion: v1
kind: Service
metadata:
  name: vmselect
  namespace: kube-vm
  labels:
    app: vmselect
spec:
  type: NodePort
  ports:
  - port: 8481
    targetPort: vmselect-tcp
    protocol: TCP
  selector:
    app: vmselect
